In [1]:
import numpy as np
import tensorflow as tf
 
params = tf.constant(np.reshape(np.arange(30), [5, 6]))
indices = tf.constant([0, 2, 3])
selected = tf.gather(params, indices)

sess = tf.Session()
print(sess.run(params))
print(sess.run(selected))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
